// This file is autogenerated by scripts/transpilePrompts.ts
// Do not edit this file directly.
/**
 * @module
 */

export type SystemPrompt = "questions";
export declare const SystemPrompts: SystemPrompt[];
export declare const systemPromptsDictionary: { [key in SystemPrompt]: string };

export type UserPrompt = "";
export declare const UserPrompts: UserPrompt[];
export declare const userPromptsDictionary: { [key in UserPrompt]: string };
