import { motion } from "motion/react";

import { OnboardingStepBaseProps } from "@/components/blocks/Onboarding/index";
import { Button } from "@/components/ui/button";
import {
    Card,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";

export default function Relying({ onNext }: OnboardingStepBaseProps) {
    return (
        <>
            <Card asChild className="w-full max-w-sm">
                <motion.div
                    initial={{ opacity: 0, y: -20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: 20 }}
                >
                    <CardHeader>
                        <CardTitle>Relying on Gifterpal</CardTitle>
                        <CardDescription>
                            This one&apos;s not in the terms, but just a
                            friendly reminder: Gifterpal is a tool to help you
                            brainstorm gift ideas. While we strive to provide
                            accurate and helpful suggestions, please remember
                            that the suggestions generated by Gifterpal are
                            based on patterns in data and may not always be
                            perfect or suitable for every situation.
                        </CardDescription>
                        <CardDescription>
                            You should not rely solely on Gifterpal for making
                            gift decisions, especially for those close to you.
                            Always consider the recipient&apos;s preferences,
                            needs, and context when choosing a gift.{" "}
                            <strong>
                                Relying on AI services for things like this
                                removes some of the personal touch and heatfelt
                                consideration that makes gift-giving special.
                            </strong>{" "}
                            Gifterpal is here to assist you, but the final
                            decision should always be yours!
                        </CardDescription>
                    </CardHeader>
                    <CardFooter className="justify-end">
                        <Button onClick={onNext}>Next</Button>
                    </CardFooter>
                </motion.div>
            </Card>
            <motion.p
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 20 }}
                className="max-w-sm text-center text-xs text-muted-foreground"
            >
                Last one, promise.
            </motion.p>
        </>
    );
}
